"""Deterministic QA for an outbound document (red until Codex builds it).

Plan: docs/plans/2026-09-16-father.md. The handoff's rule: a second model is useful but not sufficient;
the produced bytes are parsed, rendered and checked against required facts. Fixtures are built here with
python-docx and the fictional Alex Rivera at Northwind.

CONTRACT (companion/doc_qa.py)
  @dataclass(frozen=True) Finding: kind: str; where: str; text: str
      kinds: "dash" (em dash, en dash, spaced hyphen, double hyphen), "provider_name" (Claude, ChatGPT, GPT,
      OpenAI, Anthropic, Codex, Gemini, Grok, Copilot; whole words, case-insensitive), "placeholder" (TODO,
      TBD, lorem, "[INSERT", "{{", "[["), "metadata" (core author/last_modified_by not in allowed_authors;
      any comment; any tracked change), "fact_missing" (a facts value absent from the body text),
      "truncation" (llm.TRUNCATION_MARKER)
      where: "body" | "header" | "footer" | "comment" | "docProps"
  class RenderUnavailable(RuntimeError)
  class Renderer(ABC): render(path: Path, out_dir: Path) -> list[Path]   # page images, in order
  class WordRenderer(Renderer), class PdfToPpmRenderer(Renderer)          # real ones, verified by a real run
  @dataclass Report: findings: list[Finding]; rendered_pages: list[Path]; render_error: str | None
      ok -> bool: no findings, at least one rendered page, render_error None
  inspect_docx(path, *, facts: dict[str, str] | None = None, allowed_authors: frozenset[str] = frozenset(),
               renderer: Renderer | None = None, out_dir: Path | None = None) -> Report
      renderer None -> render_error "renderer_not_configured"; RenderUnavailable -> render_error its message
"""
from pathlib import Path

import pytest
from docx import Document

from companion.llm import TRUNCATION_MARKER


@pytest.fixture
def dq():
    import companion.doc_qa as doc_qa

    return doc_qa


class OnePage:
    """A renderer that writes one page file; never touches Word."""

    def __init__(self):
        self.calls = 0

    def render(self, path, out_dir):
        self.calls += 1
        page = Path(out_dir) / "page-1.png"
        page.write_bytes(b"\x89PNG fake")
        return [page]


class Broken:
    def render(self, path, out_dir):
        from companion.doc_qa import RenderUnavailable

        raise RenderUnavailable("word_not_running")


def _doc(tmp_path, body, *, footer="", author="Northwind", comment=None):
    d = Document()
    d.core_properties.author = author
    d.core_properties.last_modified_by = author
    p = d.add_paragraph(body)
    if footer:
        d.sections[0].footer.paragraphs[0].text = footer
    if comment:
        d.add_comment(p.runs, text=comment, author=author)
    path = tmp_path / "letter.docx"
    d.save(path)
    return path


CLEAN = "Dear Alex Rivera, the Northwind invoice for March totals 1,250.00 and is attached. Kind regards, Sam."


def test_clean_document_with_rendered_page_is_ok(dq, tmp_path):
    path = _doc(tmp_path, CLEAN)
    report = dq.inspect_docx(path, facts={"recipient": "Alex Rivera", "amount": "1,250.00"},
                             allowed_authors=frozenset({"Northwind"}), renderer=OnePage(), out_dir=tmp_path / "pages")
    assert report.findings == [] and len(report.rendered_pages) == 1 and report.render_error is None
    assert report.ok is True


def test_planted_defects_are_each_found_where_they_are(dq, tmp_path):
    body = "Dear Alex Rivera — the invoice is TODO and totals 1,250.00." + TRUNCATION_MARKER
    path = _doc(tmp_path, body, footer="Generated by Claude", author="python-docx", comment="check this")
    report = dq.inspect_docx(path, facts={"amount": "1,250.00", "date": "2026-03-31"},
                             allowed_authors=frozenset({"Northwind"}), renderer=OnePage(), out_dir=tmp_path / "pages")
    kinds = {(f.kind, f.where) for f in report.findings}
    assert {("dash", "body"), ("placeholder", "body"), ("truncation", "body"), ("provider_name", "footer"),
            ("metadata", "docProps"), ("metadata", "comment"), ("fact_missing", "body")} <= kinds
    assert not any(f.kind == "fact_missing" and "1,250.00" in f.text for f in report.findings)
    assert report.ok is False


def test_spaced_hyphen_and_double_hyphen_count_as_dashes(dq, tmp_path):
    report = dq.inspect_docx(_doc(tmp_path, "Totals - see below -- attached."), allowed_authors=frozenset({"Northwind"}),
                             renderer=OnePage(), out_dir=tmp_path / "p")
    assert [f.kind for f in report.findings] == ["dash", "dash"]


def test_provider_names_match_whole_words_only(dq, tmp_path):
    report = dq.inspect_docx(_doc(tmp_path, "The Codexa plant and the gemini spacecraft, per OpenAI."),
                             allowed_authors=frozenset({"Northwind"}), renderer=OnePage(), out_dir=tmp_path / "p")
    assert sorted(f.text.lower() for f in report.findings if f.kind == "provider_name") == ["gemini", "openai"]


def test_missing_renderer_is_recorded_never_silent(dq, tmp_path):
    path = _doc(tmp_path, CLEAN)
    none = dq.inspect_docx(path, allowed_authors=frozenset({"Northwind"}))
    assert none.findings == [] and none.rendered_pages == [] and none.render_error == "renderer_not_configured"
    assert none.ok is False
    broken = dq.inspect_docx(path, allowed_authors=frozenset({"Northwind"}), renderer=Broken(), out_dir=tmp_path / "p")
    assert broken.render_error == "word_not_running" and broken.ok is False


def test_real_renderers_exist_on_the_abc(dq):
    assert issubclass(dq.WordRenderer, dq.Renderer) and issubclass(dq.PdfToPpmRenderer, dq.Renderer)
