"""jobs table

Revision ID: 3e6d32be30d5
Revises: 553057a3be76
Create Date: 2026-09-06 05:05:27.107137
"""
import sqlalchemy as sa
from alembic import op

revision = '3e6d32be30d5'
down_revision = '553057a3be76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='queued', nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('progress', sa.Text(), server_default='[]', nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.String(length=64), nullable=True),
    sa.Column('finished_at', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
