"""initial relational stores

Revision ID: 553057a3be76
Revises: 
Create Date: 2026-09-06 05:02:18.023030
"""
import sqlalchemy as sa
from alembic import op

revision = '553057a3be76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='applied', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_takeaway', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('next_review_at', sa.String(length=64), nullable=False),
    sa.Column('review_count', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_streak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_review_date', sa.String(length=32), nullable=True),
    sa.CheckConstraint('id = 0', name='single_row'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('due_at', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('done', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminders')
    op.drop_table('learning_streak')
    op.drop_table('learning_items')
    op.drop_table('job_applications')
    # ### end Alembic commands ###
