"""outreach contacts

Revision ID: 5e0d66b61880
Revises: 3e6d32be30d5
Create Date: 2026-09-06 14:10:55.105730
"""
import sqlalchemy as sa
from alembic import op


revision = '5e0d66b61880'
down_revision = '3e6d32be30d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outreach_contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('company', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('profile_url', sa.Text(), nullable=True),
    sa.Column('relation', sa.Text(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('follow_up', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='drafted', nullable=False),
    sa.Column('sent_at', sa.String(length=64), nullable=True),
    sa.Column('follow_up_at', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outreach_contacts')
    # ### end Alembic commands ###
