"""job application resume_path

Revision ID: 8f4f8496ae73
Revises: 5e0d66b61880
Create Date: 2026-09-06 22:55:43.558341
"""
import sqlalchemy as sa
from alembic import op


revision = '8f4f8496ae73'
down_revision = '5e0d66b61880'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_path', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.drop_column('resume_path')

    # ### end Alembic commands ###
