"""focus sessions

Revision ID: 95948f84f255
Revises: 8f4f8496ae73
Create Date: 2026-09-08 09:55:31.298271
"""
import sqlalchemy as sa
from alembic import op


revision = '95948f84f255'
down_revision = '8f4f8496ae73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('focus_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('condition', sa.String(length=32), nullable=False),
    sa.Column('task', sa.Text(), server_default='', nullable=False),
    sa.Column('planned_minutes', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.String(length=64), nullable=False),
    sa.Column('ended_at', sa.String(length=64), nullable=True),
    sa.Column('abandoned', sa.Integer(), server_default='0', nullable=False),
    sa.Column('probe_start_ms', sa.Float(), nullable=True),
    sa.Column('probe_start_lapses', sa.Integer(), nullable=True),
    sa.Column('probe_end_ms', sa.Float(), nullable=True),
    sa.Column('probe_end_lapses', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('focus_sessions')
    # ### end Alembic commands ###
